# *Plot*

```{r}
plot(cars)
```

# **Function**

```{r}
# Define a function to
get_votes <- function(prompt = "Enter votes: ") {
  votes <- as.integer(readline(prompt))
}

mario <- get_votes("Mario: ")
peach <- get_votes("Peach: ")
bowser <- get_votes("Bowser: ")

total <- sum(mario, peach, bowser)
cat("Total votes: ", total)
```

**ifelse**

```{r}
get_votes <- function(prompt = "Enter votes: ") {
  votes <- suppressWarnings(as.integer(readline(prompt)))
  # if NA, return 0.
  ifelse(is.na(votes), 0, votes)
}

mario <- get_votes("Mario: ")
peach <- get_votes("Peach: ")
bowser <- get_votes("Bowser: ")

total <- sum(mario, peach, bowser)
cat("Total votes: ", total)
```

# ***Loop***

```{r}
get_votes <- function(prompt = "Enter votes: ") {
  repeat {
    votes <- suppressWarnings(as.integer(readline(prompt)))
    # if NA, return 0.
    if (!is.na(votes)) {
      return(votes)
    }
  }
}

# Use a loop to get votes.
for (i in c("Mario", "Peach", "Bowser")) {
  votes <- get_votes(paste0(i, ": "))
}

total <- sum(mario, peach, bowser)
cat("Total votes: ", total)
```

# *Apply*

```{r}
# MARGIN = 1 -> rows; MARGIN = 2 -> columns
apply(cars$mpg, MARGIN = 2, FUN = sum)
```
